name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用 Ubuntu 20.04 而不是最新的
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential libssl-dev libffi-dev python3-dev
        sudo apt install -y zlib1g-dev libncurses5-dev libncursesw5-dev
        sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt install -y libffi7
    
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install cython==0.29.30
        pip install buildozer kivy==2.1.0 openpyxl pyjnius
    
    - name: Create buildozer.spec
      run: |
        echo "[app]
        title = 奶牛体况评分
        package.name = cowscoreapp
        package.domain = com.example
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas,ttf
        version = 1.0
        requirements = python3,kivy==2.1.0,openpyxl,pyjnius
        android.permissions = WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE
        android.api = 30
        android.minapi = 21
        android.sdk = 24
        android.ndk = 23b
        android.arch = armeabi-v7a
        orientation = landscape
        fullscreen = 0
        source.include_patterns = *.ttf,*.otf

        [buildozer]
        log_level = 2" > buildozer.spec
    
    - name: Build APK
      run: |
        buildozer android debug
      timeout-minutes: 60
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        if-no-files-found: warn
